export const ActionTypes = {
  CONNECT: "CONNECT",
  POOL_DETAIL:"POOL_DETAIL",
  REMAIN_TIME:"REMAIN_TIME",
  USER_RANK:"USER_RANK",
  WITHDRAW_INFO:"WITHDRAW_INFO",
  LATEST_DEPOSIT:"LATEST_DEPOSIT"

};
export const FETCH_NFTS_REQUEST = 'FETCH_NFTS_REQUEST';
export const FETCH_NFTS_SUCCESS = 'FETCH_NFTS_SUCCESS';
export const FETCH_NFTS_FAILURE = 'FETCH_NFTS_FAILURE';
